name: tests

on: ['push', 'pull_request']

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3, 8.4]
        stability: [prefer-lowest, prefer-stable]

    name: tests P${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: sqlite, pdo_sqlite, pdo

      - name: install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          composer update --${{ matrix.stability }} --no-interaction --prefer-dist --optimize-autoloader

      - name: execute tests
        run: vendor/bin/pest --ci
